#Include quad\main.ahk
#Include ravine\main.ahk
#Include infernal\main.ahk
#Include workshop\main.ahk
#Include sanctuary\main.ahk
#Include dark_castle\main.ahk
#Include hashtag_ouch\main.ahk
#Include dark_dungeons\main.ahk
#Include muddy_puddles\main.ahk
#Include bloody_puddles\main.ahk
#Include flooded_valley\main.ahk