#Include monkey_meadow.ahk
#Include tree_stump.ahk
#Include town_center.ahk
#Include middle_of_the_road.ahk
#Include one_two_tree.ahk
#Include scrapyard.ahk
#Include the_cabin.ahk
#Include resort.ahk
#Include skates.ahk
#Include lotus_island.ahk
#Include candy_falls.ahk
#Include winter_park.ahk
