#Include quad.ahk
#Include infernal.ahk
#Include dark_castle.ahk
#Include ravine_easy.ahk
#Include hashtag_ouch.ahk
#Include dark_dungeons.ahk
#Include muddy_puddles.ahk
#Include workshop_easy.ahk
#Include bloody_puddles.ahk
#Include flooded_valley.ahk
#Include sanctuary_easy.ahk