#Include dark_easy.ahk
#Include ouch_easy.ahk
#Include quad_easy.ahk
#Include muddy_easy.ahk
#Include bloody_easy.ahk
#Include ravine_easy.ahk
#Include flooded_easy.ahk
#Include infernal_easy.ahk
#Include workshop_easy.ahk
#Include sanctuary_easy.ahk
